dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - chmod +x mvnw
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-es
  - mysql -e 'CREATE DATABASE beavarts;'
script: mvn test -Dspring-boot.run.profiles=mysql-travis
