dist: xenial
language: java
jdk: openjdk8
services:
  - mysql
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE beavarts;'
install:
  - pip install codacy-coverage


script:
  - mvn clean package -DskipTests=true
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report Java -r target/site/jacoco/*.xml
branches:
  only:
  - main
  - develop
  - CodacyImpl
