dist: xenial
language: java
jdk: openjdk8
services:
  - mysql
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE beavarts;'
install:
  - pip install codacy-coverage
before_script:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download

script:
  - mvn clean package -DskipTests=true 
  - mvn test -Dspring-boot.run.profiles=mysql-travis
  - mvn clean -Dspring-boot.run.profiles=mysql-travis org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r target/site/jacoco/*.xml
branches:
  only:
  - master
  - develop
  - travis-configuration-sprint2
  - fixtestanuncios-issue#102

 

deploy:
  provider: heroku
  strategy: git
  apikey: 
    master: $HEROKU_AUTH_TOKEN_PROD
  app:
    master: beavarts
